site_name: abb_motion_program_exec
site_description: Python package to execute motion commands on ABB robots and log results
site_url: https://abb-motion-program-exec.readthedocs.io/en/latest/
repo_url: https://github.com/rpiRobotics/abb_motion_program_exec

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            show_root_heading: true
            members_order: source

nav:
  - Home: index.md
  - Robot Setup:
      - Overview: robot_setup.md
      - Single Robot: robot_setup_manual.md
      - Multi-Move: robot_multimove_setup_manual.md
  - EGM: egm.md
  - API Reference:
      - Overview: abb_motion_program_exec/api_reference.md
      - abb_motion_program_exec: abb_motion_program_exec/api/abb_motion_program_exec.md
      - AsyncIO Client: abb_motion_program_exec/api/abb_motion_program_exec_client_aio.md
